#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FITOCRACY.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="FitocracyDB")]
	public partial class FitocracyDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertTracks(Tracks instance);
    partial void UpdateTracks(Tracks instance);
    partial void DeleteTracks(Tracks instance);
    partial void InsertWorkouts(Workouts instance);
    partial void UpdateWorkouts(Workouts instance);
    partial void DeleteWorkouts(Workouts instance);
    partial void InsertLevels(Levels instance);
    partial void UpdateLevels(Levels instance);
    partial void DeleteLevels(Levels instance);
    partial void InsertEntrenadores(Entrenadores instance);
    partial void UpdateEntrenadores(Entrenadores instance);
    partial void DeleteEntrenadores(Entrenadores instance);
    partial void InsertUsuario_Entrenamiento(Usuario_Entrenamiento instance);
    partial void UpdateUsuario_Entrenamiento(Usuario_Entrenamiento instance);
    partial void DeleteUsuario_Entrenamiento(Usuario_Entrenamiento instance);
    partial void InsertEntrenamientos(Entrenamientos instance);
    partial void UpdateEntrenamientos(Entrenamientos instance);
    partial void DeleteEntrenamientos(Entrenamientos instance);
    partial void InsertTarjetas(Tarjetas instance);
    partial void UpdateTarjetas(Tarjetas instance);
    partial void DeleteTarjetas(Tarjetas instance);
    partial void InsertUsuarios(Usuarios instance);
    partial void UpdateUsuarios(Usuarios instance);
    partial void DeleteUsuarios(Usuarios instance);
    #endregion
		
		public FitocracyDBDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["FitocracyDBConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public FitocracyDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public FitocracyDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public FitocracyDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public FitocracyDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Tracks> Tracks
		{
			get
			{
				return this.GetTable<Tracks>();
			}
		}
		
		public System.Data.Linq.Table<Workouts> Workouts
		{
			get
			{
				return this.GetTable<Workouts>();
			}
		}
		
		public System.Data.Linq.Table<Levels> Levels
		{
			get
			{
				return this.GetTable<Levels>();
			}
		}
		
		public System.Data.Linq.Table<Entrenadores> Entrenadores
		{
			get
			{
				return this.GetTable<Entrenadores>();
			}
		}
		
		public System.Data.Linq.Table<Usuario_Entrenamiento> Usuario_Entrenamiento
		{
			get
			{
				return this.GetTable<Usuario_Entrenamiento>();
			}
		}
		
		public System.Data.Linq.Table<Entrenamientos> Entrenamientos
		{
			get
			{
				return this.GetTable<Entrenamientos>();
			}
		}
		
		public System.Data.Linq.Table<Tarjetas> Tarjetas
		{
			get
			{
				return this.GetTable<Tarjetas>();
			}
		}
		
		public System.Data.Linq.Table<Usuarios> Usuarios
		{
			get
			{
				return this.GetTable<Usuarios>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tracks")]
	public partial class Tracks : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _IdTrack;
		
		private string _Nombre;
		
		private string _Link;
		
		private int _Series;
		
		private int _Repeticiones;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdTrackChanging(string value);
    partial void OnIdTrackChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnLinkChanging(string value);
    partial void OnLinkChanged();
    partial void OnSeriesChanging(int value);
    partial void OnSeriesChanged();
    partial void OnRepeticionesChanging(int value);
    partial void OnRepeticionesChanged();
    #endregion
		
		public Tracks()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdTrack", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string IdTrack
		{
			get
			{
				return this._IdTrack;
			}
			set
			{
				if ((this._IdTrack != value))
				{
					this.OnIdTrackChanging(value);
					this.SendPropertyChanging();
					this._IdTrack = value;
					this.SendPropertyChanged("IdTrack");
					this.OnIdTrackChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Link", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Link
		{
			get
			{
				return this._Link;
			}
			set
			{
				if ((this._Link != value))
				{
					this.OnLinkChanging(value);
					this.SendPropertyChanging();
					this._Link = value;
					this.SendPropertyChanged("Link");
					this.OnLinkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Series", DbType="Int NOT NULL")]
		public int Series
		{
			get
			{
				return this._Series;
			}
			set
			{
				if ((this._Series != value))
				{
					this.OnSeriesChanging(value);
					this.SendPropertyChanging();
					this._Series = value;
					this.SendPropertyChanged("Series");
					this.OnSeriesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Repeticiones", DbType="Int NOT NULL")]
		public int Repeticiones
		{
			get
			{
				return this._Repeticiones;
			}
			set
			{
				if ((this._Repeticiones != value))
				{
					this.OnRepeticionesChanging(value);
					this.SendPropertyChanging();
					this._Repeticiones = value;
					this.SendPropertyChanged("Repeticiones");
					this.OnRepeticionesChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Workouts")]
	public partial class Workouts : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Nombre;
		
		private int _Puntos;
		
		private string _Tracks;
		
		private System.Nullable<int> _Id_Workout;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnPuntosChanging(int value);
    partial void OnPuntosChanged();
    partial void OnTracksChanging(string value);
    partial void OnTracksChanged();
    partial void OnId_WorkoutChanging(System.Nullable<int> value);
    partial void OnId_WorkoutChanged();
    #endregion
		
		public Workouts()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(100) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Puntos", DbType="Int NOT NULL")]
		public int Puntos
		{
			get
			{
				return this._Puntos;
			}
			set
			{
				if ((this._Puntos != value))
				{
					this.OnPuntosChanging(value);
					this.SendPropertyChanging();
					this._Puntos = value;
					this.SendPropertyChanged("Puntos");
					this.OnPuntosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tracks", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string Tracks
		{
			get
			{
				return this._Tracks;
			}
			set
			{
				if ((this._Tracks != value))
				{
					this.OnTracksChanging(value);
					this.SendPropertyChanging();
					this._Tracks = value;
					this.SendPropertyChanged("Tracks");
					this.OnTracksChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Workout", DbType="Int")]
		public System.Nullable<int> Id_Workout
		{
			get
			{
				return this._Id_Workout;
			}
			set
			{
				if ((this._Id_Workout != value))
				{
					this.OnId_WorkoutChanging(value);
					this.SendPropertyChanging();
					this._Id_Workout = value;
					this.SendPropertyChanged("Id_Workout");
					this.OnId_WorkoutChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Levels")]
	public partial class Levels : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Level;
		
		private int _Points;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnLevelChanging(int value);
    partial void OnLevelChanged();
    partial void OnPointsChanging(int value);
    partial void OnPointsChanged();
    #endregion
		
		public Levels()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Level]", Storage="_Level", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Level
		{
			get
			{
				return this._Level;
			}
			set
			{
				if ((this._Level != value))
				{
					this.OnLevelChanging(value);
					this.SendPropertyChanging();
					this._Level = value;
					this.SendPropertyChanged("Level");
					this.OnLevelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Points", DbType="Int NOT NULL")]
		public int Points
		{
			get
			{
				return this._Points;
			}
			set
			{
				if ((this._Points != value))
				{
					this.OnPointsChanging(value);
					this.SendPropertyChanging();
					this._Points = value;
					this.SendPropertyChanged("Points");
					this.OnPointsChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Entrenadores")]
	public partial class Entrenadores : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Id_Entrenador;
		
		private string _Nombre;
		
		private string _Apellidos;
		
		private string _Descripcion;
		
		private System.Data.Linq.Binary _Foto;
		
		private EntitySet<Entrenamientos> _Entrenamientos;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_EntrenadorChanging(string value);
    partial void OnId_EntrenadorChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnApellidosChanging(string value);
    partial void OnApellidosChanged();
    partial void OnDescripcionChanging(string value);
    partial void OnDescripcionChanged();
    partial void OnFotoChanging(System.Data.Linq.Binary value);
    partial void OnFotoChanged();
    #endregion
		
		public Entrenadores()
		{
			this._Entrenamientos = new EntitySet<Entrenamientos>(new Action<Entrenamientos>(this.attach_Entrenamientos), new Action<Entrenamientos>(this.detach_Entrenamientos));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Entrenador", DbType="VarChar(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Id_Entrenador
		{
			get
			{
				return this._Id_Entrenador;
			}
			set
			{
				if ((this._Id_Entrenador != value))
				{
					this.OnId_EntrenadorChanging(value);
					this.SendPropertyChanging();
					this._Id_Entrenador = value;
					this.SendPropertyChanged("Id_Entrenador");
					this.OnId_EntrenadorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Apellidos", DbType="VarChar(200)")]
		public string Apellidos
		{
			get
			{
				return this._Apellidos;
			}
			set
			{
				if ((this._Apellidos != value))
				{
					this.OnApellidosChanging(value);
					this.SendPropertyChanging();
					this._Apellidos = value;
					this.SendPropertyChanged("Apellidos");
					this.OnApellidosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="VarChar(1000) NOT NULL", CanBeNull=false)]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this.OnDescripcionChanging(value);
					this.SendPropertyChanging();
					this._Descripcion = value;
					this.SendPropertyChanged("Descripcion");
					this.OnDescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Foto", DbType="Image NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary Foto
		{
			get
			{
				return this._Foto;
			}
			set
			{
				if ((this._Foto != value))
				{
					this.OnFotoChanging(value);
					this.SendPropertyChanging();
					this._Foto = value;
					this.SendPropertyChanged("Foto");
					this.OnFotoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Entrenadores_Entrenamientos", Storage="_Entrenamientos", ThisKey="Id_Entrenador", OtherKey="Id_Entrenador")]
		public EntitySet<Entrenamientos> Entrenamientos
		{
			get
			{
				return this._Entrenamientos;
			}
			set
			{
				this._Entrenamientos.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Entrenamientos(Entrenamientos entity)
		{
			this.SendPropertyChanging();
			entity.Entrenadores = this;
		}
		
		private void detach_Entrenamientos(Entrenamientos entity)
		{
			this.SendPropertyChanging();
			entity.Entrenadores = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Usuario_Entrenamiento")]
	public partial class Usuario_Entrenamiento : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id_Usuario;
		
		private string _Id_Entrenamiento;
		
		private EntityRef<Entrenamientos> _Entrenamientos;
		
		private EntityRef<Usuarios> _Usuarios;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_UsuarioChanging(int value);
    partial void OnId_UsuarioChanged();
    partial void OnId_EntrenamientoChanging(string value);
    partial void OnId_EntrenamientoChanged();
    #endregion
		
		public Usuario_Entrenamiento()
		{
			this._Entrenamientos = default(EntityRef<Entrenamientos>);
			this._Usuarios = default(EntityRef<Usuarios>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Usuario", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Id_Usuario
		{
			get
			{
				return this._Id_Usuario;
			}
			set
			{
				if ((this._Id_Usuario != value))
				{
					if (this._Usuarios.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnId_UsuarioChanging(value);
					this.SendPropertyChanging();
					this._Id_Usuario = value;
					this.SendPropertyChanged("Id_Usuario");
					this.OnId_UsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Entrenamiento", DbType="VarChar(9) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Id_Entrenamiento
		{
			get
			{
				return this._Id_Entrenamiento;
			}
			set
			{
				if ((this._Id_Entrenamiento != value))
				{
					if (this._Entrenamientos.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnId_EntrenamientoChanging(value);
					this.SendPropertyChanging();
					this._Id_Entrenamiento = value;
					this.SendPropertyChanged("Id_Entrenamiento");
					this.OnId_EntrenamientoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Entrenamientos_Usuario_Entrenamiento", Storage="_Entrenamientos", ThisKey="Id_Entrenamiento", OtherKey="Id_Entrenamiento", IsForeignKey=true)]
		public Entrenamientos Entrenamientos
		{
			get
			{
				return this._Entrenamientos.Entity;
			}
			set
			{
				Entrenamientos previousValue = this._Entrenamientos.Entity;
				if (((previousValue != value) 
							|| (this._Entrenamientos.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Entrenamientos.Entity = null;
						previousValue.Usuario_Entrenamiento.Remove(this);
					}
					this._Entrenamientos.Entity = value;
					if ((value != null))
					{
						value.Usuario_Entrenamiento.Add(this);
						this._Id_Entrenamiento = value.Id_Entrenamiento;
					}
					else
					{
						this._Id_Entrenamiento = default(string);
					}
					this.SendPropertyChanged("Entrenamientos");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Usuarios_Usuario_Entrenamiento", Storage="_Usuarios", ThisKey="Id_Usuario", OtherKey="Id_Usuario", IsForeignKey=true)]
		public Usuarios Usuarios
		{
			get
			{
				return this._Usuarios.Entity;
			}
			set
			{
				Usuarios previousValue = this._Usuarios.Entity;
				if (((previousValue != value) 
							|| (this._Usuarios.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Usuarios.Entity = null;
						previousValue.Usuario_Entrenamiento.Remove(this);
					}
					this._Usuarios.Entity = value;
					if ((value != null))
					{
						value.Usuario_Entrenamiento.Add(this);
						this._Id_Usuario = value.Id_Usuario;
					}
					else
					{
						this._Id_Usuario = default(int);
					}
					this.SendPropertyChanged("Usuarios");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Entrenamientos")]
	public partial class Entrenamientos : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Id_Entrenamiento;
		
		private string _Familia;
		
		private string _NombreEntrenamiento;
		
		private string _Id_Entrenador;
		
		private double _Precio;
		
		private int _Duracion;
		
		private string _Descripcion;
		
		private System.Data.Linq.Binary _Foto;
		
		private string _Who;
		
		private string _Goals;
		
		private string _Requirements;
		
		private string _WhatYouGet;
		
		private EntitySet<Usuario_Entrenamiento> _Usuario_Entrenamiento;
		
		private EntityRef<Entrenadores> _Entrenadores;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_EntrenamientoChanging(string value);
    partial void OnId_EntrenamientoChanged();
    partial void OnFamiliaChanging(string value);
    partial void OnFamiliaChanged();
    partial void OnNombreEntrenamientoChanging(string value);
    partial void OnNombreEntrenamientoChanged();
    partial void OnId_EntrenadorChanging(string value);
    partial void OnId_EntrenadorChanged();
    partial void OnPrecioChanging(double value);
    partial void OnPrecioChanged();
    partial void OnDuracionChanging(int value);
    partial void OnDuracionChanged();
    partial void OnDescripcionChanging(string value);
    partial void OnDescripcionChanged();
    partial void OnFotoChanging(System.Data.Linq.Binary value);
    partial void OnFotoChanged();
    partial void OnWhoChanging(string value);
    partial void OnWhoChanged();
    partial void OnGoalsChanging(string value);
    partial void OnGoalsChanged();
    partial void OnRequirementsChanging(string value);
    partial void OnRequirementsChanged();
    partial void OnWhatYouGetChanging(string value);
    partial void OnWhatYouGetChanged();
    #endregion
		
		public Entrenamientos()
		{
			this._Usuario_Entrenamiento = new EntitySet<Usuario_Entrenamiento>(new Action<Usuario_Entrenamiento>(this.attach_Usuario_Entrenamiento), new Action<Usuario_Entrenamiento>(this.detach_Usuario_Entrenamiento));
			this._Entrenadores = default(EntityRef<Entrenadores>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Entrenamiento", DbType="VarChar(9) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Id_Entrenamiento
		{
			get
			{
				return this._Id_Entrenamiento;
			}
			set
			{
				if ((this._Id_Entrenamiento != value))
				{
					this.OnId_EntrenamientoChanging(value);
					this.SendPropertyChanging();
					this._Id_Entrenamiento = value;
					this.SendPropertyChanged("Id_Entrenamiento");
					this.OnId_EntrenamientoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Familia", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Familia
		{
			get
			{
				return this._Familia;
			}
			set
			{
				if ((this._Familia != value))
				{
					this.OnFamiliaChanging(value);
					this.SendPropertyChanging();
					this._Familia = value;
					this.SendPropertyChanged("Familia");
					this.OnFamiliaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreEntrenamiento", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string NombreEntrenamiento
		{
			get
			{
				return this._NombreEntrenamiento;
			}
			set
			{
				if ((this._NombreEntrenamiento != value))
				{
					this.OnNombreEntrenamientoChanging(value);
					this.SendPropertyChanging();
					this._NombreEntrenamiento = value;
					this.SendPropertyChanged("NombreEntrenamiento");
					this.OnNombreEntrenamientoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Entrenador", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string Id_Entrenador
		{
			get
			{
				return this._Id_Entrenador;
			}
			set
			{
				if ((this._Id_Entrenador != value))
				{
					if (this._Entrenadores.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnId_EntrenadorChanging(value);
					this.SendPropertyChanging();
					this._Id_Entrenador = value;
					this.SendPropertyChanged("Id_Entrenador");
					this.OnId_EntrenadorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Precio", DbType="Float NOT NULL")]
		public double Precio
		{
			get
			{
				return this._Precio;
			}
			set
			{
				if ((this._Precio != value))
				{
					this.OnPrecioChanging(value);
					this.SendPropertyChanging();
					this._Precio = value;
					this.SendPropertyChanged("Precio");
					this.OnPrecioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Duracion", DbType="Int NOT NULL")]
		public int Duracion
		{
			get
			{
				return this._Duracion;
			}
			set
			{
				if ((this._Duracion != value))
				{
					this.OnDuracionChanging(value);
					this.SendPropertyChanging();
					this._Duracion = value;
					this.SendPropertyChanged("Duracion");
					this.OnDuracionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this.OnDescripcionChanging(value);
					this.SendPropertyChanging();
					this._Descripcion = value;
					this.SendPropertyChanged("Descripcion");
					this.OnDescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Foto", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary Foto
		{
			get
			{
				return this._Foto;
			}
			set
			{
				if ((this._Foto != value))
				{
					this.OnFotoChanging(value);
					this.SendPropertyChanging();
					this._Foto = value;
					this.SendPropertyChanged("Foto");
					this.OnFotoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Who", DbType="VarChar(MAX)")]
		public string Who
		{
			get
			{
				return this._Who;
			}
			set
			{
				if ((this._Who != value))
				{
					this.OnWhoChanging(value);
					this.SendPropertyChanging();
					this._Who = value;
					this.SendPropertyChanged("Who");
					this.OnWhoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Goals", DbType="VarChar(MAX)")]
		public string Goals
		{
			get
			{
				return this._Goals;
			}
			set
			{
				if ((this._Goals != value))
				{
					this.OnGoalsChanging(value);
					this.SendPropertyChanging();
					this._Goals = value;
					this.SendPropertyChanged("Goals");
					this.OnGoalsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Requirements", DbType="VarChar(MAX)")]
		public string Requirements
		{
			get
			{
				return this._Requirements;
			}
			set
			{
				if ((this._Requirements != value))
				{
					this.OnRequirementsChanging(value);
					this.SendPropertyChanging();
					this._Requirements = value;
					this.SendPropertyChanged("Requirements");
					this.OnRequirementsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WhatYouGet", DbType="VarChar(MAX)")]
		public string WhatYouGet
		{
			get
			{
				return this._WhatYouGet;
			}
			set
			{
				if ((this._WhatYouGet != value))
				{
					this.OnWhatYouGetChanging(value);
					this.SendPropertyChanging();
					this._WhatYouGet = value;
					this.SendPropertyChanged("WhatYouGet");
					this.OnWhatYouGetChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Entrenamientos_Usuario_Entrenamiento", Storage="_Usuario_Entrenamiento", ThisKey="Id_Entrenamiento", OtherKey="Id_Entrenamiento")]
		public EntitySet<Usuario_Entrenamiento> Usuario_Entrenamiento
		{
			get
			{
				return this._Usuario_Entrenamiento;
			}
			set
			{
				this._Usuario_Entrenamiento.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Entrenadores_Entrenamientos", Storage="_Entrenadores", ThisKey="Id_Entrenador", OtherKey="Id_Entrenador", IsForeignKey=true)]
		public Entrenadores Entrenadores
		{
			get
			{
				return this._Entrenadores.Entity;
			}
			set
			{
				Entrenadores previousValue = this._Entrenadores.Entity;
				if (((previousValue != value) 
							|| (this._Entrenadores.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Entrenadores.Entity = null;
						previousValue.Entrenamientos.Remove(this);
					}
					this._Entrenadores.Entity = value;
					if ((value != null))
					{
						value.Entrenamientos.Add(this);
						this._Id_Entrenador = value.Id_Entrenador;
					}
					else
					{
						this._Id_Entrenador = default(string);
					}
					this.SendPropertyChanged("Entrenadores");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Usuario_Entrenamiento(Usuario_Entrenamiento entity)
		{
			this.SendPropertyChanging();
			entity.Entrenamientos = this;
		}
		
		private void detach_Usuario_Entrenamiento(Usuario_Entrenamiento entity)
		{
			this.SendPropertyChanging();
			entity.Entrenamientos = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tarjetas")]
	public partial class Tarjetas : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id_Usuario;
		
		private string _CardNumber;
		
		private string _SecurityCode;
		
		private string _Caducity;
		
		private EntityRef<Usuarios> _Usuarios;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_UsuarioChanging(int value);
    partial void OnId_UsuarioChanged();
    partial void OnCardNumberChanging(string value);
    partial void OnCardNumberChanged();
    partial void OnSecurityCodeChanging(string value);
    partial void OnSecurityCodeChanged();
    partial void OnCaducityChanging(string value);
    partial void OnCaducityChanged();
    #endregion
		
		public Tarjetas()
		{
			this._Usuarios = default(EntityRef<Usuarios>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Usuario", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Id_Usuario
		{
			get
			{
				return this._Id_Usuario;
			}
			set
			{
				if ((this._Id_Usuario != value))
				{
					if (this._Usuarios.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnId_UsuarioChanging(value);
					this.SendPropertyChanging();
					this._Id_Usuario = value;
					this.SendPropertyChanged("Id_Usuario");
					this.OnId_UsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CardNumber", DbType="VarChar(16) NOT NULL", CanBeNull=false)]
		public string CardNumber
		{
			get
			{
				return this._CardNumber;
			}
			set
			{
				if ((this._CardNumber != value))
				{
					this.OnCardNumberChanging(value);
					this.SendPropertyChanging();
					this._CardNumber = value;
					this.SendPropertyChanged("CardNumber");
					this.OnCardNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SecurityCode", DbType="VarChar(3) NOT NULL", CanBeNull=false)]
		public string SecurityCode
		{
			get
			{
				return this._SecurityCode;
			}
			set
			{
				if ((this._SecurityCode != value))
				{
					this.OnSecurityCodeChanging(value);
					this.SendPropertyChanging();
					this._SecurityCode = value;
					this.SendPropertyChanged("SecurityCode");
					this.OnSecurityCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Caducity", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Caducity
		{
			get
			{
				return this._Caducity;
			}
			set
			{
				if ((this._Caducity != value))
				{
					this.OnCaducityChanging(value);
					this.SendPropertyChanging();
					this._Caducity = value;
					this.SendPropertyChanged("Caducity");
					this.OnCaducityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Usuarios_Tarjetas", Storage="_Usuarios", ThisKey="Id_Usuario", OtherKey="Id_Usuario", IsForeignKey=true)]
		public Usuarios Usuarios
		{
			get
			{
				return this._Usuarios.Entity;
			}
			set
			{
				Usuarios previousValue = this._Usuarios.Entity;
				if (((previousValue != value) 
							|| (this._Usuarios.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Usuarios.Entity = null;
						previousValue.Tarjetas = null;
					}
					this._Usuarios.Entity = value;
					if ((value != null))
					{
						value.Tarjetas = this;
						this._Id_Usuario = value.Id_Usuario;
					}
					else
					{
						this._Id_Usuario = default(int);
					}
					this.SendPropertyChanged("Usuarios");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Usuarios")]
	public partial class Usuarios : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id_Usuario;
		
		private string _Email;
		
		private string _Username;
		
		private string _Password;
		
		private System.Data.Linq.Binary _Foto;
		
		private int _Points;
		
		private System.Nullable<int> _Age;
		
		private string _Description;
		
		private int _Level;
		
		private string _WorkOuts;
		
		private System.Nullable<System.DateTime> _Birthday;
		
		private EntitySet<Usuario_Entrenamiento> _Usuario_Entrenamiento;
		
		private EntityRef<Tarjetas> _Tarjetas;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_UsuarioChanging(int value);
    partial void OnId_UsuarioChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnUsernameChanging(string value);
    partial void OnUsernameChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    partial void OnFotoChanging(System.Data.Linq.Binary value);
    partial void OnFotoChanged();
    partial void OnPointsChanging(int value);
    partial void OnPointsChanged();
    partial void OnAgeChanging(System.Nullable<int> value);
    partial void OnAgeChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    partial void OnLevelChanging(int value);
    partial void OnLevelChanged();
    partial void OnWorkOutsChanging(string value);
    partial void OnWorkOutsChanged();
    partial void OnBirthdayChanging(System.Nullable<System.DateTime> value);
    partial void OnBirthdayChanged();
    #endregion
		
		public Usuarios()
		{
			this._Usuario_Entrenamiento = new EntitySet<Usuario_Entrenamiento>(new Action<Usuario_Entrenamiento>(this.attach_Usuario_Entrenamiento), new Action<Usuario_Entrenamiento>(this.detach_Usuario_Entrenamiento));
			this._Tarjetas = default(EntityRef<Tarjetas>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Usuario", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id_Usuario
		{
			get
			{
				return this._Id_Usuario;
			}
			set
			{
				if ((this._Id_Usuario != value))
				{
					this.OnId_UsuarioChanging(value);
					this.SendPropertyChanging();
					this._Id_Usuario = value;
					this.SendPropertyChanged("Id_Usuario");
					this.OnId_UsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Username", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Username
		{
			get
			{
				return this._Username;
			}
			set
			{
				if ((this._Username != value))
				{
					this.OnUsernameChanging(value);
					this.SendPropertyChanging();
					this._Username = value;
					this.SendPropertyChanged("Username");
					this.OnUsernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this.OnPasswordChanging(value);
					this.SendPropertyChanging();
					this._Password = value;
					this.SendPropertyChanged("Password");
					this.OnPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Foto", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary Foto
		{
			get
			{
				return this._Foto;
			}
			set
			{
				if ((this._Foto != value))
				{
					this.OnFotoChanging(value);
					this.SendPropertyChanging();
					this._Foto = value;
					this.SendPropertyChanged("Foto");
					this.OnFotoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Points", DbType="Int NOT NULL")]
		public int Points
		{
			get
			{
				return this._Points;
			}
			set
			{
				if ((this._Points != value))
				{
					this.OnPointsChanging(value);
					this.SendPropertyChanging();
					this._Points = value;
					this.SendPropertyChanged("Points");
					this.OnPointsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Age", DbType="Int")]
		public System.Nullable<int> Age
		{
			get
			{
				return this._Age;
			}
			set
			{
				if ((this._Age != value))
				{
					this.OnAgeChanging(value);
					this.SendPropertyChanging();
					this._Age = value;
					this.SendPropertyChanged("Age");
					this.OnAgeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="VarChar(140)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Level]", Storage="_Level", DbType="Int NOT NULL")]
		public int Level
		{
			get
			{
				return this._Level;
			}
			set
			{
				if ((this._Level != value))
				{
					this.OnLevelChanging(value);
					this.SendPropertyChanging();
					this._Level = value;
					this.SendPropertyChanged("Level");
					this.OnLevelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WorkOuts", DbType="VarChar(MAX)")]
		public string WorkOuts
		{
			get
			{
				return this._WorkOuts;
			}
			set
			{
				if ((this._WorkOuts != value))
				{
					this.OnWorkOutsChanging(value);
					this.SendPropertyChanging();
					this._WorkOuts = value;
					this.SendPropertyChanged("WorkOuts");
					this.OnWorkOutsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Birthday", DbType="Date")]
		public System.Nullable<System.DateTime> Birthday
		{
			get
			{
				return this._Birthday;
			}
			set
			{
				if ((this._Birthday != value))
				{
					this.OnBirthdayChanging(value);
					this.SendPropertyChanging();
					this._Birthday = value;
					this.SendPropertyChanged("Birthday");
					this.OnBirthdayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Usuarios_Usuario_Entrenamiento", Storage="_Usuario_Entrenamiento", ThisKey="Id_Usuario", OtherKey="Id_Usuario")]
		public EntitySet<Usuario_Entrenamiento> Usuario_Entrenamiento
		{
			get
			{
				return this._Usuario_Entrenamiento;
			}
			set
			{
				this._Usuario_Entrenamiento.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Usuarios_Tarjetas", Storage="_Tarjetas", ThisKey="Id_Usuario", OtherKey="Id_Usuario", IsUnique=true, IsForeignKey=false)]
		public Tarjetas Tarjetas
		{
			get
			{
				return this._Tarjetas.Entity;
			}
			set
			{
				Tarjetas previousValue = this._Tarjetas.Entity;
				if (((previousValue != value) 
							|| (this._Tarjetas.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Tarjetas.Entity = null;
						previousValue.Usuarios = null;
					}
					this._Tarjetas.Entity = value;
					if ((value != null))
					{
						value.Usuarios = this;
					}
					this.SendPropertyChanged("Tarjetas");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Usuario_Entrenamiento(Usuario_Entrenamiento entity)
		{
			this.SendPropertyChanging();
			entity.Usuarios = this;
		}
		
		private void detach_Usuario_Entrenamiento(Usuario_Entrenamiento entity)
		{
			this.SendPropertyChanging();
			entity.Usuarios = null;
		}
	}
}
#pragma warning restore 1591
